- name: Install zookeeper 
  shell: |
    wget https://archive.apache.org/dist/kafka/0.10.2.1/kafka_2.12-0.10.2.1.tgz
    tar -xvzf kafka_2.12-0.10.2.1.tgz
    rm kafka_2.12-0.10.2.1.tgz
    mv kafka_2.12-0.10.2.1 kafka

- name: Copy zookeeper config file
  copy:
    src: zookeeper
    dest: /etc/init.d/zookeeper
    owner: root
    group: root
    mode: '0744'
    backup: yes

- name: update rc.d
  command: update-rc.d zookeeper defaults
  ignore_errors: yes

- name: Start service zookeeper
  service:
    name: zookeeper
    state: started

- name: check zookeeper status
  command: nc -vz localhost 2181
  register: command_result

- debug:
    var: command_result

#- name: start zookeeper if port 2181 not listening 
#  service: name=zookeeper state=started
#  when: "'failed' in command_result.stderr"

- name: check zookeeper response
  shell: |
     echo "ruok" | nc localhost 2181 
  register: ruok_result
  ignore_errors: yes

- debug:
    var: ruok_result
 
