- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Install a list of packages
  apt:
    pkg:
    - wget
    - ca-certificates
    - zip 
    - net-tools
    - vim 
    - nano
    - tar
    - netcat
    - openjdk-8-jdk

- name: Set swap to minimum without disable
  sysctl:
    name: vm.swappiness
    value: '1'
    state: present

- name: update hosts file
  blockinfile:
    path: /etc/hosts
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: |	
      192.168.57.50 kafka1
      192.168.57.50 zookeeper1
      192.168.57.51 kafka2
      192.168.57.51 zookeeper2
      192.168.57.52 kafka3
      192.168.57.52 zookeeper3
    backup: yes
    state: present

- name: remove /etc/machine-id
  file:
    path: /etc/machine-id
    state: absent
- name: remove /var/lib/dbus/machine-id
  file:
    path: /var/lib/dbus/machine-id
    state: absent
- name: generate new machine-id
  command: systemd-machine-id-setup

- name: download zookeeper
  shell: |
    wget https://archive.apache.org/dist/kafka/0.10.2.1/kafka_2.12-0.10.2.1.tgz
    tar -xvzf kafka_2.12-0.10.2.1.tgz
    rm kafka_2.12-0.10.2.1.tgz
    mv kafka_2.12-0.10.2.1 kafka

- name: Reboot machine
  reboot:
    reboot_timeout: 120
